# Generated by Django 5.1.4 on 2025-01-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
