# Generated by Django 5.1.4 on 2025-01-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_subscription_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cv_customizations_used',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='recommendations_used',
        ),
    ]
