# Generated by Django 5.1.4 on 2025-01-03 09:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_ats_optimized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='NOT_APPLIED', max_length=20)),
                ('match_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cv_text', models.TextField()),
                ('generated_cv_text', models.TextField()),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated_cvs/docx/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated_cvs/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cvs', to='jobs.cvtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cvs', to=settings.AUTH_USER_MODEL)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cvs', to='jobs.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matching_keywords', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('ats_recommendations', models.JSONField(default=list)),
                ('skill_matches', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_analysis', to='jobs.jobapplication')),
            ],
        ),
    ]
