# Generated by Django 5.1.4 on 2025-01-09 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_cvtemplate_jobapplication_generatedcv_cvanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_rationale', models.TextField()),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='scraped_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='bookmarked_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('MYJOBMAG', 'MyJobMag'), ('RELIEFWEB', 'ReliefWeb'), ('CORPORATESTAFFING', 'Corporate Staffing')], default='None', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedcv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_title'], name='jobs_job_job_tit_ca70ea_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobs_job_locatio_8b2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['date_posted'], name='jobs_job_date_po_dc50ec_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source'], name='jobs_job_source_e2155e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_job_created_1b3a4d_idx'),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['user', 'match_score'], name='jobs_jobmat_user_id_af10b0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['user', 'is_bookmarked'], name='jobs_jobmat_user_id_45a162_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['user', 'is_hidden'], name='jobs_jobmat_user_id_2004ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobmatch',
            unique_together={('user', 'job')},
        ),
    ]
