# Generated by Django 5.1.4 on 2025-01-09 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobmatch_rename_scraped_at_job_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
