# Generated by Django 5.1.4 on 2025-01-09 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_hidden_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
