# Generated by Django 5.1.4 on 2025-01-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_bookmarked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='match_score',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('SCREENING', 'In Screening'), ('INTERVIEWING', 'Interviewing'), ('TECHNICAL_ROUND', 'Technical Round'), ('OFFER_RECEIVED', 'Offer Received'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_DECLINED', 'Offer Declined'), ('REJECTED', 'Application Rejected'), ('GHOSTED', 'No Response')], default='NOT_APPLIED', max_length=20),
        ),
    ]
