# Generated by Django 5.1.4 on 2025-01-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobapplication_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
