# Generated by Django 5.1.4 on 2025-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobapplication_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
