# Generated by Django 5.1.4 on 2024-12-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_recommendations_limit', models.IntegerField(default=0)),
                ('cv_customization_limit', models.IntegerField(default=0)),
                ('cover_letter_customization_limit', models.IntegerField(default=0)),
                ('priority_support', models.BooleanField(default=False)),
                ('trial_period_days', models.IntegerField(default=0)),
                ('features', models.TextField()),
            ],
        ),
    ]
