# Generated by Django 5.1.4 on 2025-01-10 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_plan_features_plan_job_alerts_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedJobTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(max_length=255)),
                ('title_2', models.CharField(max_length=255)),
                ('title_3', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Extracted Job Titles',
            },
        ),
    ]
