# Generated by Django 5.1.4 on 2025-01-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_extractedjobtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='years_of_experience',
            field=models.CharField(default='0-1 years', max_length=255),
        ),
    ]
