# Generated by Django 5.1.4 on 2025-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_preferences_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='years_of_experience',
            field=models.CharField(max_length=255),
        ),
    ]
