# Generated by Django 5.1.4 on 2025-01-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_preferences_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='weekly_applications',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
